Photovoir/Models/Seller/NewProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Photovoir.Models.Seller
{
    public class NewProductViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Price { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Tags { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }
    }
}

Photovoir/Models/Seller/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Photovoir.Models.Seller
{
    public class ProductViewModel
    {
    }
}

Photovoir/Models/Seller/ProfileViewModel.cs
using Photovoir.Data.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Photovoir.Models.Seller
{
    public class ProfileViewModel
    {
        public List<Product> UserPosts { get; set; }
    }
}

Photovoir/Controllers/SellerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Photovoir.Data.Products;
using Photovoir.Data.User;
using Photovoir.Interfaces.Repositories.Products;
using Photovoir.Models.Seller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Photovoir.Controllers
{
    public class SellerController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        public SellerController(IProductRepository productRepository, 
            UserManager<ApplicationUser> userManager)
        {
            _productRepository = productRepository;
            _userManager = userManager;
        }
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            var post = await _productRepository.GetByUserIdAsync(user.Id);
            var model = new ProfileViewModel
            {
                UserPosts = post
            };
            return View(model);
        }

        public IActionResult Products()
        {
            return View();
        }

        public IActionResult NewProduct()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewProduct(NewProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var product = new Product
            {
                AuthorId = user.Id,
                Name = model.Name,
                Price = Convert.ToDouble(model.Price),
                Description = model.Description,
                Tags = model.Tags
            };

            await _productRepository.AddAsync(product);

            return RedirectToAction(nameof(Profile));
        }
    }
}

Photovoir/Views/Seller/NewProduct.cshtml
@using Photovoir.Models.Seller
@model NewProductViewModel
    <!-- Breadcrumb -->
    <div class="py-3 bg-gray-100">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 my-2">
                    <h1 class="m-0 h4 text-center text-lg-start">Seller Account</h1>
                </div>
                <div class="col-lg-6 my-2">
                    <ol class="breadcrumb dark-link m-0 small justify-content-center justify-content-lg-end">
                        <li class="breadcrumb-item"><a class="text-nowrap" asp-controller="Seller" asp-action="Profile"><i class="bi bi-home"></i>Profile</a></li>
                        <li class="breadcrumb-item"><a class="text-nowrap"><i class="bi bi-home"></i>New Product</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->
    <div class="py-6">
        <div class="container">
            <div class="card mb-5">
                <div class="card-header py-3">
                    <h5 class="m-0">New Product</h5>
                </div>
                <div class="card-body">
                    <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
                        <div class="row">
                            <div class="col-sm-6 mb-3">
                                <label class="form-label">Photograph</label>
                                <input class="form-control" type="file" id="formFile">
                            </div>
                            <div class="col-sm-6 mb-3">
                                <label asp-for="Name" class="form-label">Name<span class="text-danger">*</span></label>
                                <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-sm-6 mb-3">
                                <label asp-for="Price" class="form-label">Price<span class="text-danger">*</span></label>
                                <input asp-for="Price" type="text" class="form-control" placeholder="Price">
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="col-sm-6 mb-3">
                                <label asp-for="Tags" class="form-label"></label>
                                <select asp-for="Tags" class="form-select" required="">
                                    <option value="Select">Select </option>
                                    <option value="Landscape">Landscape </option>
                                    <option value="Portrait">Portrait</option>
                                    <option value="Food">Food</option>
                                    <option value="Architecture">Architecture</option>
                                    <option value="Sports">Sports</option>
                                </select>
                                <span asp-validation-for="Tags" class="text-danger"></span>
                            </div>
                            <div class=" mb-3">
                                <label asp-for="Description" class="form-label">Description<span class="text-danger">*</span></label>
                                <input asp-for="Description" type="text" class="form-control" placeholder="Description">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="col-12 pt-2">
                                <button class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }

Photovoir/Views/Seller/Profile.cshtml
@using Photovoir.Models.Seller
@using Photovoir.Data.Products
@model ProfileViewModel
@inject UserManager<ApplicationUser> UserManager
@inject IUserEmailStore<ApplicationUser> EmailStore
<!-- Breadcrumb -->
<div class="py-3 bg-gray-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 my-2">
                <h1 class="m-0 h4 text-center text-lg-start">Seller Account</h1>
            </div>
            <div class="col-lg-6 my-2">
                <ol class="breadcrumb dark-link m-0 small justify-content-center justify-content-lg-end">
                    <li class="breadcrumb-item"><a class="text-nowrap"><i class="bi bi-home"></i>Profile</a></li>
                    <li class="breadcrumb-item"><a class="text-nowrap" asp-controller="Seller" asp-action="NewProduct"><i class="bi bi-home"></i>New Product</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumb -->
<!-- Table -->
<div class="py-6">
    <div class="container">
        <div class="row">
            <!-- Profile Menu -->
            <div class="col-lg-4 pb-4 pb-lg-0 col-xxl-3  pe-xxl-5">
                <div class="bg-white border border-bottom-0 shadow-lg">
                    <div class="d-flex p-3 align-items-center">
                        <div class="avatar avatar-lg rounded-circle">
                            <img src="/Custom/img/profilepic.jpg" title="" alt="">
                        </div>
                        <div class="col ps-3">
                            <h6 class="m-0">@UserManager.GetUserName(User)</h6>
                            <small><a href="#">@await EmailStore.GetEmailAsync(await UserManager.GetUserAsync(User), new System.Threading.CancellationToken())</a></small>
                        </div>
                    </div>
                    <div class="bg-gray-200 p-3 border-bottom border-top">
                        <h6 class="m-0">Dashboard</h6>
                    </div>
                    <ul class="list-unstyled mb-0 theme-link">
                        <li class="border-bottom mb-0">
                            <a class="nav-link-style d-flex align-items-center p-3" asp-controller="Seller" asp-action="NewProduct">
                                <i class="bi bi-bookmark me-2"></i>New Product
                            </a>
                        </li>
                        <li class="border-bottom mb-0">
                            <a class="nav-link-style d-flex align-items-center p-3" asp-controller="Manage" asp-action="Index">
                                <i class="bi bi-bookmark me-2"></i>Account Settings
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table-responsive col-lg-8 col-xxl-9">
                <table class="table table-bordered table-hover mb-0">
                    <thead class="text-700 bg-gray-200">
                        <tr>
                            <th class="fw-600">Product #</th>
                            <th class="fw-600">Product Name</th>
                            <th class="fw-600">Tags</th>
                            <th class="fw-600 text-end">Price</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (Product p in Model.UserPosts)
                        {
                            <tr>
                                <td class="p-3"><a class="link-dark" href="#order-details" data-bs-toggle="modal">@p.Id</a></td>
                                <td class="p-3">@p.Name</td>
                                <td class="p-3"><span class="badge bg-info m-0">@p.Tags</span></td>
                                <td class="p-3 text-end">$@p.Price</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>