Photovoir/Controllers/ShopController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Photovoir.Data.Products;
using Photovoir.Interfaces.Repositories.Products;
using Photovoir.Models.Shop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Photovoir.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class ShopController : Controller
    {
        private readonly ILogger<ShopController> _logger;
        private readonly IProductRepository _productRepository;

        public ShopController(ILogger<ShopController> logger, IProductRepository productRepository)
        {
            _logger = logger;
            _productRepository = productRepository;
        }
        public async Task<IActionResult> Index()
        {
            var model = new ShopViewModel
            {
                Products = new List<Product>()
            };

            var result = await _productRepository.GetAllAsync();
            foreach(Product p in result)
            {
                model.Products.Add(p);
            }

            return View(model);
        }

        public IActionResult ProductDetails()
        {
            return View();
        }
    }
}

Photovoir/Views/Shared/_FooterPartial.cshtml
<!-- End Main -->
<!-- Footer -->
<footer class="d-flex flex-column min-vh-40 bg-dark footer footer-border-top light">
    <div class="footer-top py-6">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3 my-1">
                    <div class="pb-3">
                        <a asp-controller="Home" asp-action="Index">
                            <img src="/Custom/img/LogoBlack.png" title="" alt="">
                        </a>
                    </div>
                    <address class="white-link mb-4">
                        <p class="text-white-85 mb-2">This, That & The Other Street, <br /> Nova Scotia, Canada</p>
                        <p class="mb-2"><a class="border-bottom border-secondary">support@domain.com</a></p>
                        <p class="mb-2"><a class="border-bottom border-secondary">123-456-7890</a></p>
                    </address>
                    <div class="nav white-link fs-5">
                        <a class="me-3">
                            <i class="bi bi-facebook"></i>
                        </a>
                        <a class="me-3">
                            <i class="bi bi-twitter"></i>
                        </a>
                        <a class="me-3">
                            <i class="bi bi-instagram"></i>
                        </a>
                        <a class="me-3">
                            <i class="bi bi-linkedin"></i>
                        </a>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3 my-4">
                    <h6 class="text-uppercase mb-5 text-white">
                        Support
                    </h6>
                    <ul class="list-unstyled white-link footer-link-1 m-0">
                        <li class="pb-2">
                            <a asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="pb-2">
                            <a asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="pb-2">
                            <a asp-controller="Home" asp-action="FAQ">FAQ</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 my-4">
                    <h6 class="text-uppercase mb-5 text-white">
                        Policies
                    </h6>
                    <ul class="list-unstyled white-link footer-link-1 m-0">
                        <li class="pb-2">
                            <a href="#">Privacy Policy</a>
                        </li>
                        <li class="pb-2">
                            <a href="#">Terms of use</a>
                        </li>
                        <li class="pb-2">
                            <a href="#">Shipping</a>
                        </li>
                        <li class="pb-2">
                            <a href="#">Return</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-6 col-lg-3 my-4">
                    <h6 class="text-uppercase mb-5 text-white">
                        Newsletter
                    </h6>
                    <p class="text-white-85">Join our Newsletter to keep up to date!</p>
                    <form>
                        <div class="input-group">
                            <input type="email" class="form-control" placeholder="Enter your email">
                            <button class="btn btn-primary" type="submit"><i class="bi bi-envelope"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom py-2 footer-border-top light small">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start py-1">
                    <p class="m-0 text-white-85">© 2021 copyright by <a href="#" class="text-reset">Team-04</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

Photovoir/Views/Shared/_HeaderPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager
<header class="header-main bg-white header-dark header-option-1">
    <div class="header-top pt-3 pb-2 py-md-2 py-lg-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 col-lg-3 text-center text-md-start">
                    <!-- Logo -->
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="/Custom/img/Logo.png" title="" alt="">
                    </a>
                    <!-- Logo -->
                    <hr class="d-md-none mt-3 mb-2">
                </div>
                <!--Search Bar Start-->
                <div class="col-lg-6 d-none d-lg-block">
                    <form>
                        <div class="input-group">
                            <!-- Search input -->
                            <input class="form-control form-control-sm shadow-none px-3" type="text" name="search" placeholder="What are you looking for?">
                            <!-- Search button -->
                            <a asp-controller="Shop" asp-action="Index" type="button" class="btn btn-dark btn-sm shadow-none px-3">
                                <i class="bi bi-search"></i>
                            </a>
                        </div>
                    </form>
                </div>
                <!--Search Bar End-->
                <!-- Right Side Top Nav Bar -->
                <div class="col-md-6 col-lg-3">
                    <div class="nav flex-nowrap align-items-center justify-content-md-end header-right header-right-light w-100 w-md-auto position-relative">
                        <!-- Nav Search-->
                        <div class="nav-item dropdown position-static d-lg-none">
                            <a class="nav-link" href="#" role="button" id="dropdown_myaccount" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-search"> </i>
                            </a>
                            <div class="dropdown-menu w-100 w-lg-auto">
                                <form>
                                    <div class="input-group p-3">
                                        <!-- Search input -->
                                        <input class="form-control shadow-none" type="text" name="search" placeholder="What are you looking for?">
                                        <!-- Search button -->
                                        <button type="button" class="btn btn-primary shadow-none">
                                            <i class="bi bi-search"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <partial name="_NavLoginPartial" />
                        <!-- Mobile Toggle -->
                        <button class="navbar-toggler navbar-toggler-px-light ms-auto ms-md-0 d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <!-- End Mobile Toggle -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-0">
        <div class="container">
            <!-- Start bottom Header -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto">
                    .
                    <!-- Home Drop Down -->
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                All
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                Nature
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                Architecture
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                Landscape
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                Food
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                Portrait
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">
                                Sports
                            </a>
                        </li>
                    }
                </ul>
            </div>
            <!-- End Menu -->
        </div>
    </nav>

</header>
<!-- Header End -->

Photovoir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Title -->
        <title>@ViewData["Title"] | PhotoVoir</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <!-- Favicon -->
        <link rel="shortcut icon" href="/favicon.ico">
        <!-- CSS Template -->
        <link href="/Custom/css/style.css" rel="stylesheet">
        @RenderSection("Stylesheets", false)
    </head>
    <body>
        <partial name="_HeaderPartial" />
        <div>
            <main>
                @RenderBody()
            </main>
        </div>
        <hr />
        <partial name="_FooterPartial" />
        <!-- End Footer -->
        <!-- jquery -->
        <script src="/Custom/js/jquery-3.5.1.min.js"></script>
        <!-- appear -->
        <script src="/Custom/vendor/appear/jquery.appear.js"></script>
        <!--bootstrap-->
        <script src="/Custom/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- slick carousel -->
        <script src="/Custom/vendor/slick/slick.min.js"></script>
        <!-- magnific -->
        <script src="/Custom/vendor/magnific/jquery.magnific-popup.min.js"></script>
        <!-- isotope -->
        <script src="/Custom/vendor/isotope/isotope.pkgd.min.js"></script>
        <!-- count-down -->
        <script src="/Custom/vendor/count-down/jquery.countdown.min.js"></script>
        <!-- Theme Js -->
        <script src="/Custom/js/custom.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

Photovoir/Views/Shared/_NavLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Photovoir.Interfaces.Repositories.Cart
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IShoppingCartRepository ShoppingCartRepository
@inject IUserRoleStore<ApplicationUser> UserRoleStore
<!-- Account Nav Start-->
@if (!SignInManager.IsSignedIn(User))
{
    <div>
        <a class="nav-link" asp-controller="Account" asp-action="Login">
            Sign In
        </a>
    </div>
    <div class="nav-item dropdown">
        <a class="nav-link" asp-controller="Account" asp-action="Login" role="button">
            <i class="bi bi-person-circle"> </i>
        </a>
    </div>
}
else
{
    <div class="nav-item dropdown">
        <a class="nav-link" role="button" id="dropdown_myaccount" data-bs-toggle="dropdown" data-bs-display="static" aria-haspopup="true" aria-expanded="false">
            <i>@UserManager.GetUserName(User) </i>
            <i class="bi bi-person-circle"> </i>
        </a>
        <form class="dropdown-menu dropdown-menu-hover right shadow" aria-labelledby="dropdown_myaccount" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="dropdown-item" asp-controller="Manage" asp-action="Index">My account</a>
                </li>
                @if (await UserRoleStore.IsInRoleAsync(await UserManager.GetUserAsync(User), "Seller", new System.Threading.CancellationToken()))
                {
                    <li>
                        <a class="dropdown-item" asp-controller="Seller" asp-action="Profile">Seller Profile</a>
                    </li>
                }
                <li>
                    <button type="submit" class="dropdown-item">Log out</button>
                </li>
            </ul>
        </form>
    </div>
    <!-- Wishlist -->
    <div class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-action="Wishlist">
            <i class="bi bi-heart"> </i>
        </a>
    </div>
    <!-- Cart -->
    <div class="nav-item me-md-3 me-lg-0">
        <a class="nav-link" asp-controller="Account" asp-action="ShoppingCart">
            <span class="">
                <i class="bi bi-cart"> </i>
            </span>
        </a>
    </div>
    <!-- Account Nav End -->
}